### ISSUE TITLE
Skip superlinter

### ISSUE THREAD

**Issue by claesgill** [fredrikhgrelland/terraform-nomad-postgres#52]
## What is the issue?
From time to time we experience bugs with the Github Superlinter and it could fail. Proposing that we implement a `skip-linter` label to skip the linter-test.

## Suggestion(s)/solution(s) [Optional]
Something like this should do the job: 
```yml
jobs:
  linter:
    runs-on: ubuntu-latest
    if: github.event.pull_request.labels.*.name != 'skip-linter'
    steps:
...

```

### :warning: Note
I tried to implement this, but the linter-job is set as `required` so it didn't work. I think it needs to be turned off by the repo owner to work, but I'm not sure. 

## Checklist (after created issue)
- [x] Added label(s)
- [ ] Added to project
- [ ] Added to milestone
